# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588be3ee0f3e7173ab0e3a12ab9e817b5e66e6f1f418736e22ca6d4b177dd01a992c8b335084149dee0445d06b221759d9979626226cbfbb83d346bde137621e

test:
  secret_key_base: f2c699c1a216171fb31bb42ce882713000372e1e4de390df2a7e2e7d844c24364b9f52fe3377a866ef1a03625e2943189b8f59b25aa19acfdf0789efdf2f4e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
